Frontend logging fixes
uwcirg/cosri-pain-management-summary pull request #221
Opened 2024-12-18 22:16 UTC by achen2401

Address https://www.pivotaltracker.com/story/show/188705822
- Add user info to each event logging
- Add `analytics` tag to tab/open/view events
- Prevent `cosri-frontend` tag from being added multiple times

Example JSONs posted

  ```
{
    "patient": "Barney Abbott",
    "message": "MME calculated: Name: Fentanyl Transdermal System, 0.05 mg/hr...",
    "level": "info",
    "tags": ["mme-calc", "cosri-frontend"],
    "patientName": "Barney Abbott",
    "subject": "Patient/5ee05359-57bf-4cee-8e89-91382c07e162",
    "user": "amysbubble"
  }
```
  ```
{
    "patient": "Barney Abbott",
    "message": "overview tab",
    "level": "info",
    "tags": ["tab", "analytics", "cosri-frontend"],
    "patientName": "Barney Abbott",
    "subject": "Patient/5ee05359-57bf-4cee-8e89-91382c07e162",
    "user": "amysbubble"
  }
```

2024-12-19 00:14 UTC, mcjustin approved these changes

2024-12-20 22:18 UTC, ivan-c requested changes
Thank you! I tested on dev and found a minor inconsistency with the rest of our logs

2024-12-20 22:18 UTC, ivan-c commented on src/helpers/utility.js
> +      logParams.user = userId;
Could to nest the username under `user`? 

I realized we're already following this pattern for cosri-patientsearch and the SoF backend

```suggestion
      logParams.user.username = userId;
```

2024-12-20 22:40 UTC, achen2401 commented
thank you @ivan-c for catching the inconsistency. I updated the description with updated user format in the JSON, e.g.
```
{
....
"user": { "username": "amysbubble" }
}
```

2024-12-21 02:59 UTC, ivan-c approved these changes
Found a minor issue. Test on dev and looks good otherwise!

2024-12-21 02:59 UTC, ivan-c commented on src/helpers/utility.js
> +    const userId = "amysbubble";
I think this was leftover from testing
```suggestion
    const userId = getUserIdFromAccessToken();
```

2024-12-23 15:05 UTC, merged